import { Metadata } from "next";
import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <Head>
        <meta name="description" content="Your portfolio description" />
        <meta name="keywords" content="developer, portfolio, Next.js, React" />
        <meta name="author" content="Your Name" />
        <meta property="og:title" content="Your Portfolio" />
        <meta property="og:description" content="Check out my work and projects!" />
        <meta property="og:image" content="URL_to_image_for_social_media_share" />
        <meta property="og:url" content="https://www.your-website.com" />
        <title>Your Portfolio</title>
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
